"""empty message

Revision ID: 662ee7125d62
Revises:
Create Date: 2018-05-04 21:48:21.884140

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '662ee7125d62'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('author_claim',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('true', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['author.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_foreign_key(None, 'article', 'publication', ['publication_id'], ['id'])
    op.add_column('publication', sa.Column('bias_level', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('publication', 'bias_level')
    op.drop_constraint(None, 'article', type_='foreignkey')
    op.drop_table('author_claim')
    op.drop_table('company')
    # ### end Alembic commands ###
